# Generated by Django 5.1.3 on 2024-11-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitecapturecatalog',
            name='coordinates_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SatelliteDateRetrievalPipelineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('vendor_name', models.CharField(choices=[('airbus', 'airbus'), ('blacksky', 'blacksky'), ('planet', 'planet'), ('maxar', 'maxar'), ('capella', 'capella'), ('skyfi', 'skyfi')], max_length=50)),
                ('message', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['start_datetime'], name='core_satell_start_d_2855ea_idx'), models.Index(fields=['end_datetime'], name='core_satell_end_dat_e915b4_idx')],
            },
        ),
    ]
