# Generated by Django 5.1.3 on 2024-12-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_satellitecapturecatalog_image_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitecapturecatalog',
            name='vendor_name',
            field=models.CharField(choices=[('airbus', 'airbus'), ('blacksky', 'blacksky'), ('planet', 'planet'), ('maxar', 'maxar'), ('capella', 'capella'), ('skyfi-umbra', 'skyfi-umbra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='satellitedateretrievalpipelinehistory',
            name='vendor_name',
            field=models.CharField(choices=[('airbus', 'airbus'), ('blacksky', 'blacksky'), ('planet', 'planet'), ('maxar', 'maxar'), ('capella', 'capella'), ('skyfi-umbra', 'skyfi-umbra')], max_length=50),
        ),
        migrations.CreateModel(
            name='SatelliteCaptureCatalogMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(choices=[('airbus', 'airbus'), ('blacksky', 'blacksky'), ('planet', 'planet'), ('maxar', 'maxar'), ('capella', 'capella'), ('skyfi-umbra', 'skyfi-umbra')], max_length=50)),
                ('vendor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_datetime', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vendor_name'], name='core_satell_vendor__a4598b_idx'), models.Index(fields=['vendor_id'], name='core_satell_vendor__ec64fb_idx'), models.Index(fields=['acquisition_datetime'], name='core_satell_acquisi_8a890f_idx')],
            },
        ),
    ]
