# Generated by Django 5.1.3 on 2025-01-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_satellitecapturecatalog_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitecapturecatalog',
            name='gsd',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='satellitecapturecatalog',
            name='georeferenced',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
