# Generated by Django 5.1.3 on 2025-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_satellitecapturecatalog_gsd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitecapturecatalog',
            name='gsd',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
