# Generated by Django 5.1.3 on 2025-02-08 07:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_satellitecapturecatalog_gsd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_datetime', models.DateTimeField(blank=True, null=True)),
                ('cloud_cover_percent', models.FloatField(blank=True, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(choices=[('airbus', 'airbus'), ('blacksky', 'blacksky'), ('planet', 'planet'), ('maxar', 'maxar'), ('capella', 'capella'), ('skyfi-umbra', 'skyfi-umbra')], max_length=50)),
                ('sensor', models.TextField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('sun_elevation', models.FloatField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('georeferenced', models.BooleanField(blank=True, default=False, null=True)),
                ('location_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('coordinates_record', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_uploaded', models.BooleanField(blank=True, default=False, null=True)),
                ('gsd', models.FloatField(blank=True, null=True)),
                ('offnadir', models.FloatField(blank=True, null=True)),
                ('constellation', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('azimuth_angle', models.FloatField(blank=True, null=True)),
                ('illumination_azimuth_angle', models.FloatField(blank=True, null=True)),
                ('illumination_elevation_angle', models.FloatField(blank=True, null=True)),
                ('holdback_seconds', models.FloatField(blank=True, null=True)),
                ('publication_datetime', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('geometryCentroid_lat', models.FloatField(blank=True, null=True)),
                ('geometryCentroid_lon', models.FloatField(blank=True, null=True)),
                ('coordinates_record_md5', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['acquisition_datetime'], name='core_collec_acquisi_1a74c5_idx'), models.Index(fields=['publication_datetime'], name='core_collec_publica_8db970_idx'), models.Index(fields=['vendor_name', 'acquisition_datetime'], name='core_collec_vendor__f8709d_idx'), models.Index(fields=['vendor_id', 'acquisition_datetime'], name='core_collec_vendor__2ea054_idx'), models.Index(fields=['coordinates_record_md5'], name='core_collec_coordin_593c01_idx'), models.Index(fields=['location_polygon'], name='core_collec_locatio_166a3f_idx')],
            },
        ),
    ]
