# Generated by Django 5.1.3 on 2025-02-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_collectioncatalog_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncatalog',
            name='centroid_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectioncatalog',
            name='centroid_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
