# Generated by Django 5.1.3 on 2025-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_collectioncatalog_centroid_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncatalog',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
