# Generated by Django 5.1.3 on 2024-12-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsite',
            name='site_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
