# Generated by Django 5.1.3 on 2024-12-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_user_id_groupsite_user_id_site_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='groupsite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='user_id',
            new_name='user',
        ),
    ]
