# Generated by Django 5.1.3 on 2025-01-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_group_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
