# Generated by Django 5.1.3 on 2025-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_is_deleted_group_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='new_updates_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='last_notification_count_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='site',
            name='new_updates_count',
            field=models.IntegerField(default=0),
        ),
    ]
