# Generated by Django 5.1.3 on 2025-03-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_group_new_updates_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='new_updates_count',
        ),
    ]
